
### Create a new user
POST {{host}}/api/users
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john.doe@example.com"
}

### Get all users
GET {{host}}/api/users


### Get user by email
@email = john.doe@example.com
GET {{host}}/api/users/{{email}}