@email = 

### Create a new user
POST {{host}}/api/users
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john.doe@example.com"
}

### Get all users
GET {{host}}/api/users


### Get user by email
GET {{host}}/api/users/{{email}}

### Delete user by email
DELETE {{host}}/api/users/{{email}}